name: Feature request
description: Propose a new feature or an idea for this project.
labels: enhancement
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: A clear and concise description of the feature request, including what problem it solves.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: An additional information or screenshots about the feature request.
    validations:
      required: false
